name: CI Angular app through Github Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup
              run: npm ci

            - name: Create
              run: touch ./src/environments/env.ts && echo "export const api_key = "{{secret.API_KEY}}"" > ./src/environments/env.ts

            - name: Test
              run: |
                  npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
