name: CI Angular app through Github Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup
              run: npm ci

            - name: Create
              run: touch ./src/environments/env.ts && echo "export const api_key = \"$API_KEY\";export const firebase_api_key = \"$FIREBASE_API_KEY\";export const client_id = \"$CLIENT_ID\";export const client_secret = \"$CLIENT_SECRET\"" > ./src/environments/env.ts
              env:
                API_KEY: ${{secrets.API_KEY}}
                FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
                CLIENT_ID: ${{secrets.CLIENT_ID}}
                CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}

            - name: Test
              run: |
                  npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
